### ISSUE TITLE
Build failing on new version 2.0.0

### ISSUE THREAD

**Issue by ntomallen** [radarlabs/react-native-radar#31] opened 2018-07-25 19:48 UTC
After updating `react-native-radar` to version 2.0, I've been getting some strange build errors:

```
While building module 'Foundation' imported from ../../../ios/Pods/Headers/Public/RadarSDK/RadarSDK/RadarSDK.h:8:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:72:
In file included from ../../../ios/Pods/leveldb-library/table/Block.h:10:
In file included from ../../../ios/Pods/leveldb-library/include/leveldb/iterator.h:18:
../../../ios/Pods/leveldb-library/include/leveldb/slice.h:21:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
While building module 'Foundation' imported from ../../../ios/Pods/Headers/Public/RadarSDK/RadarSDK/RadarSDK.h:8:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
While building module 'Foundation' imported from ../../../ios/Pods/Headers/Public/RadarSDK/RadarSDK/RadarSDK.h:8:
While building module 'Security' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:28:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CFBase.h>
 ~~~~~~~~^
1 error generated.
While building module 'Foundation' imported from ../../../ios/Pods/Headers/Public/RadarSDK/RadarSDK/RadarSDK.h:8:
While building module 'CFNetwork' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:9:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/CFNetwork.framework/Headers/CFNetwork.h:18:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
1 error generated.
4 errors generated.
In file included from /Users/ntomallen/source/zonder-mobile-app/node_modules/react-native-radar/ios/RNRadar.m:1:
In file included from /Users/ntomallen/source/zonder-mobile-app/node_modules/react-native-radar/ios/RNRadar.h:1:
../../../ios/Pods/Headers/Public/RadarSDK/RadarSDK/RadarSDK.h:8:9: fatal error: could not build module 'Foundation'
#import "Foundation/Foundation.h"
 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
While building module 'CoreLocation' imported from ../../../ios/Pods/Headers/Public/RadarSDK/RadarSDK/Radar.h:8:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CoreLocation.h:18:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLErrorDomain.h:9:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
1 error generated.



** BUILD FAILED **
```
I also followed the migration instructions for updating the iOS and Android modules as well. Everything seems to be working correctly on Android.

I've also been researching this error, and I none of the suggested solutions for this error worked.

**Comment by coolbrow** [comment] 2018-07-25 20:17
Thanks for the report, are you using Objective-C or Swift for your native code?

Have you tried these steps yet? https://github.com/react-native-community/react-native-google-signin/issues/361

**Comment by ntomallen** [comment] 2018-07-25 21:48
Want to add that I'm on react-native version 0.55.4.

One really strange thing is that while I was debugging this yesterday, I was able to get it to work by deleting `Pods` and running `pod install` again. HOWEVER, it **only** works with an Xcode build. The error still shows up when running `react-native run-ios` and it also still shows up on our Bitrise TestFlight build.

**Comment by ntomallen** [comment] 2018-07-26 01:45
This seems like it may be relevant, but I'm not sure what the SDK's codebase looks like: https://stackoverflow.com/a/30697222

**Comment by coolbrow** [comment] 2018-07-26 14:40
Thanks for the investigations! Would you mind describing your setup to help us better reproduce locally?

Did you use `create-react-native-app`, `create-react-app` or `react-native init` (or something else?) 

And since everything was working before the upgrade I assume you've followed the documentation and _ejected_ the app?

**Comment by coolbrow** [comment] 2018-07-26 22:32
Thanks this info is super helpful! There's no changes that I know of in particular, but it's looking like I'm wrong on that one haha. Hopefully this helps me reproduce the issue. 

Feel free to stay downgraded for the time being. While 2.0 is more optimized under the hood, you should see almost identical event and behavior with the previous version

**Comment by ntomallen** [comment] 2018-07-26 22:37
Ok! We've been struggling on Android with enter/exit events not getting passed on to the JS code while the app is in the background, so I was hoping the update might help with that.

**Comment by ntomallen** [comment] 2018-07-28 02:41
Update: You know how the react-native-radar xcodeproject gets linked to your own project? It turns out that if we **remove** the react-native-radar project from our own project, the build succeeds but results in the "native module is not defined" issue. But, if we keep the project there, the build fails with the errors above.

**Comment by coolbrow** [comment] 2018-07-30 17:39
Thanks for the added info! Unfortunately I haven't seen any of these build issues before but I'm trying a bunch of different build configurations soon to see if I can reproduce. 

All this info is super helpful and I appreciate your patience as we sort this out.

**Comment by feargswalsh92** [comment] 2018-07-30 17:51
Also this is the full error message that happens when I change to Objective C++
```
using ::size_t;
using ::memcpy;
using ::memmove;
using ::strcpy;
using ::strncpy;
using ::strcat;
using ::strncat;
using ::memcmp;
using ::strcmp;
using ::strncmp;
using ::strcoll;
using ::strxfrm;
using ::memchr;
using ::strchr;
using ::strcspn;
using ::strpbrk;
using ::strrchr;
using ::strspn;
using ::strstr;
#ifndef _LIBCPP_HAS_NO_THREAD_UNSAFE_C_FUNCTIONS
using ::strtok;
#endif
using ::memset;
using ::strerror;
using ::strlen;

_LIBCPP_END_NAMESPACE_STD

#endif  // _LIBCPP_CSTRING
```

**Comment by ntomallen** [comment] 2018-08-02 22:07
Ok, I have it reproduced in this repo: https://github.com/ntomallen/radar_test

It's private, so let me know if you have any issues accessing it. I added @coolbrow and @feargswalsh92 as collaborators.

**Comment by coolbrow** [comment] 2018-08-03 12:54
Thanks so much! I'll take a look at this and will get back to you asap

**Comment by coolbrow** [comment] 2018-08-06 15:49
@ntomallen Good news! I was able to reproduce with that sample project (thanks again) and isolated the problem to the added search paths in this commit - https://github.com/radarlabs/react-native-radar/commit/f776c38389a8970cb1f587b9fad0d3938a52c885

Going to push a fix for this ASAP and release a new version.

**Comment by coolbrow** [comment] 2018-08-06 15:55
Fixed in https://github.com/radarlabs/react-native-radar/releases/tag/2.0.2

**Closed by coolbrow** 2018-08-06 15:55 UTC
