### ISSUE TITLE
[Feature Request] Improved Categories for Radar Places

### ISSUE THREAD

**Issue by noahtallen** [radarlabs/react-native-radar#34] opened 2018-08-05 19:24 UTC
Currently, when looking at a place's categories, you see a list like this: `travel-transportation, transportation-terminal, airport, train-station` (this is for the Portland International Airport, Radar ID: `59c28b488be4c5ce940ba105`). 

In our app, we basically try to determine the "most relevant" category for a place, and then match that category to certain game content. This allows users to play our travel game. One thing that's challenging with these categories is that there isn't a clear way to discover which category is the most important. For instance, in the above example, I would expect **`airport`** to be the most relevant category to a user. 

The pattern I've noticed with the categories is basically top of the hierarchy to bottom of the hierarchy. So, this example follows this pattern: 1, 2, 3, 3. Airport and train-station are on the same level of the category hierarchy. What works a lot of the time is choosing the last category which is at deeper level than the next category. in this case, that would be "train-station", and for a pattern like 1, 2, 1, 2, 3, that would be the first occurring 2. This works okay for a lot of cases. 

What would be really nice is to see a "primary" category for a place - for instance the primary category for the Portland Airport would be "airport". While testing our app with Foursquare's location data, this worked really well, since their category list includes a boolean "primary" key which indicates which category we should use as the most relevant category to a place.

That's the first part of this request, the second being better linking to Facebook categories (or whichever provider we choose). The main reason for this is our "nearby places" feature, where the user can see which nearby places they can go to earn points in the game. Since Radar doesn't have this feature built into the SDK, we do a request to Facebook Graph API to search for places near our coordinates. The facebook place category list looks like this (Flow type format):

```js
  category_list: Array<{
    id: string,
    name: string
  }>
```

There are a couple of differences from the Radar place category list here.
1. It seems to be sorted with the "most relevant" category first. 
2. There isn't an easy way to link the facebook category back to the Radar category ID. I basically take the name, make it all lowercase, and replace the whitespace with dashes. So "Fast Food" would become "fast-food". Then I link that category "ID" back to the Radar category IDs and match it to our game content. 

These approaches seem to work alright, but they aren't quite ideal for our use case. If you could give us some guidance on this, it would be much appreciated! I'm sure one part of it might be the possibility of future place providers. Finally, thanks for developing this awesome tool and for all the hard-work you guys put into the project! :)

**Comment by nickpatrick** [comment] 2018-08-06 17:07
Hey @ntomallen, thanks so much for the thoughtful note. This is something we've been thinking about recently, too.

If we changed our category sort order so that the most relevant categories came first, and if we exposed a `facebookCategories` array with Facebook category IDs in the same order, would that solve this case for you?

Can you explain why having the Facebook category IDs in addition to the Radar category IDs is useful to you?

/cc @coolbrow

**Comment by nickpatrick** [comment] 2020-05-18 20:42
Closing as duplicate of #45.

**Closed by nickpatrick** 2020-05-18 20:42 UTC
Labels: enhancement
