### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by getinnocuous** [radarlabs/react-native-radar#191] opened 2022-07-14 12:46 UTC
## Summary

Are there any plans to add TypeScript definitions to this project?

**Comment by disrae** [comment] 2023-07-27 23:08
Missing declarations file... for searchability 😬

**Comment by ChromeQ** [comment] 2024-04-11 13:38
Duplicate of https://github.com/radarlabs/react-native-radar/issues/52. Can be closed?

**Closed** 2024-04-14 12:42 UTC
